# Define stages once at the top
stages:
  - sanity
  - test
  # - lint
  - secret-detection
  # sast stage is provided by the template; it will be added automatically

# Include security templates (they bring their own jobs and stages)
# include:
#   - template: Security/SAST.gitlab-ci.yml
#   - template: Security/Secret-Detection.gitlab-ci.yml

# variables:
#   SECRET_DETECTION_ENABLED: 'true'

default:
  tags:
    - docker
  before_script:
    - apt-get update
    - apt-get install -y software-properties-common
    - add-apt-repository universe
    - apt-get update
    - apt-get install -y iverilog verilator curl python3-dev
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - source $HOME/.local/bin/env
    - uv sync --active

sanity:
  stage: sanity
  timeout: 10m
  script:
  - chmod +x ./scripts/sanity.sh
  - ./scripts/sanity.sh > ./build/logs/gitlab_runner_sanity.log 2>&1
  artifacts:
    paths:
      - ./build/logs/
    when: always

test:
  stage: test
  timeout: 1h
  script:
    - chmod +x ./scripts/mcore_regr.sh
    - ./scripts/mcore_regr.sh > ./build/logs/gitlab_runner_test.log 2>&1
  artifacts:
    paths:
      - ./build/logs/
    when: always
