# Define stages once at the top
stages:
  - test
  # - lint
  - secret-detection
  # sast stage is provided by the template; it will be added automatically

# Include security templates (they bring their own jobs and stages)
# include:
#   - template: Security/SAST.gitlab-ci.yml
#   - template: Security/Secret-Detection.gitlab-ci.yml

# variables:
#   SECRET_DETECTION_ENABLED: 'true'

default:
  tags:
    - docker
  before_script:
    - apt-get update
    - apt-get install -y software-properties-common
    - add-apt-repository universe
    - apt-get update
    - apt-get install -y iverilog verilator curl python3-dev
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - source $HOME/.local/bin/env
    - uv sync --active

# The test job needs iverilog and Python deps; security jobs don't
test:
  stage: test
  script:
    - chmod +x ./scripts/mcore_regr.sh
    - ./scripts/mcore_regr.sh
  artifacts:
    paths:
      - ./build/logs/               # if you want to keep simulation logs
    when: always

# lint:
#   stage: lint
#   before_script:
#     - apt-get update
#     - apt-get install -y verilator
#   script:
#     - source ./.venv/bin/activate
#     - python3 ./generators/MastrovitoVerilog.py
#     - verilator --lint-only -Wall ./rtl/GF_Mastrovito_Multiplier_Adder_Deg10.v


# Security jobs are already provided by the templates – do not redefine them.
# They will run in their respective stages.